### ISSUE TITLE
Add FS type in partition list to differentiate largest partitions 

### ISSUE THREAD

**Issue by aboukirev** [ahoneybun/live-disk-recovery#1]
Add FS type to the lsblk output to differentiate largest partitions. 

For instance, I have Pop!_OS and Windows partitions of roughly similar size on the same physical disk.  One would have crypto-LUKS file system and another ntfs.  That would not help when running two Linux distributions (Fedora and Arch) on the same disk.  But it helps avoiding mistakes in some cases.

**Comment by ahoneybun** [comment]
@aboukirev thank you for the great idea! I've fixed this in this commit https://github.com/ahoneybun/live-disk-recovery/commit/78bb9f8bee06fd4c0b312383e6f208825fd577ca .
